#!/usr/bin/env python3
"""
Mastiff AI - Kernel Bridge
Persistent Python execution environment for data analysis.
Receives JSON requests via stdin, executes code, returns results via stdout.
Supports: pandas, numpy, matplotlib, seaborn, plotly, scipy, sklearn.
"""

import sys
import json
import os
import traceback
import base64
from datetime import date, datetime, time
from io import BytesIO

# Preload common libraries for faster execution
import pandas as pd
import numpy as np

try:
    import matplotlib
    matplotlib.use('Agg')  # Non-interactive backend
    import matplotlib.pyplot as plt
    import seaborn as sns
    sns.set_theme(style="whitegrid", palette="colorblind")
    HAS_MPL = True
except ImportError:
    HAS_MPL = False

try:
    import plotly.express as px
    import plotly.graph_objects as go
    import plotly.io as pio
    from plotly.subplots import make_subplots as _make_subplots

    DEFAULT_COLORWAY = [
        '#0B6E99', '#FF7F0E', '#2CA02C', '#D62728',
        '#9467BD', '#8C564B', '#17BECF', '#BCBD22'
    ]

    pio.templates['mastiff'] = go.layout.Template(
        layout=go.Layout(
            colorway=DEFAULT_COLORWAY,
            font=dict(family='IBM Plex Sans, DejaVu Sans, Arial', size=12, color='#1f2937'),
            paper_bgcolor='white',
            plot_bgcolor='white',
        )
    )
    pio.templates['mastiff'].layout.colorscale = dict(
        sequential=px.colors.sequential.Viridis,
        diverging=px.colors.diverging.RdBu,
        sequentialminus=px.colors.sequential.Blues
    )
    pio.templates.default = 'mastiff'
    HAS_PLOTLY = True
except ImportError:
    HAS_PLOTLY = False

try:
    from scipy import stats as scipy_stats
    HAS_SCIPY = True
except ImportError:
    HAS_SCIPY = False

try:
    from sklearn import preprocessing, cluster, decomposition, ensemble, linear_model, metrics
    HAS_SKLEARN = True
except ImportError:
    HAS_SKLEARN = False


class SafeJSONEncoder(json.JSONEncoder):
    """JSON encoder that handles pandas/numpy types safely."""
    def default(self, obj):
        if obj is pd.NaT:
            return None
        if isinstance(obj, np.datetime64):
            return None if np.isnat(obj) else str(obj)
        if isinstance(obj, pd.Timestamp):
            return str(obj)
        if isinstance(obj, (datetime, date, time)):
            return obj.isoformat()
        if isinstance(obj, pd.Timedelta):
            return str(obj)
        if isinstance(obj, (np.integer,)):
            return int(obj)
        if isinstance(obj, (np.floating,)):
            f = float(obj)
            if f != f or f == float('inf') or f == float('-inf'):
                return None
            return f
        if isinstance(obj, (np.bool_,)):
            return bool(obj)
        if isinstance(obj, (np.ndarray,)):
            return obj.tolist()
        if isinstance(obj, (bytes, bytearray)):
            return obj.decode('utf-8', errors='replace')
        return super().default(obj)


# Persistent session state across requests
session_state = {
    'dfs': {},
    'file_sources': {},
    'variables': {},
    'history': []
}


def read_csv_flexible(filepath: str, forced_sep: str = None) -> pd.DataFrame:
    """Read CSV/TSV files with delimiter and encoding fallback."""
    encodings = ['utf-8', 'utf-8-sig', 'latin-1', 'cp1252']
    separators = [forced_sep] if forced_sep else [None, ',', ';', '\t', '|']
    last_error = None

    for encoding in encodings:
        for sep in separators:
            kwargs = {
                'encoding': encoding,
                'low_memory': False,
            }

            if sep is None:
                kwargs['sep'] = None
                kwargs['engine'] = 'python'
            else:
                kwargs['sep'] = sep

            try:
                df = pd.read_csv(filepath, **kwargs)

                if not forced_sep and df.shape[1] <= 1 and len(df.columns) > 0:
                    header_text = str(df.columns[0])
                    if any(sym in header_text for sym in [',', ';', '\t', '|'] if sym != sep):
                        continue

                return df
            except Exception as exc:
                last_error = exc

    if last_error:
        raise last_error

    return pd.read_csv(filepath, low_memory=False)


def read_json_flexible(filepath: str) -> pd.DataFrame:
    """Read JSON arrays/objects and line-delimited JSON files."""
    try:
        return pd.read_json(filepath)
    except ValueError:
        return pd.read_json(filepath, lines=True)


def _columns_look_autogenerated(df: pd.DataFrame) -> bool:
    """Check if column names look auto-generated (e.g. 'Unnamed: 0')."""
    unnamed_count = sum(1 for c in df.columns if 'unnamed' in str(c).lower())
    return unnamed_count > len(df.columns) * 0.5


def _is_usable_frame(df) -> bool:
    """Return True when *df* contains real data (not an error sentinel)."""
    if not isinstance(df, pd.DataFrame) or df.empty:
        return False
    # Error/failure DataFrames created by load_files have only a 'load_error' column.
    if list(df.columns) == ['load_error']:
        return False
    return True


def _normalize_file_id(raw_file_id) -> str:
    """Normalize client-provided file ids for stable dataframe keys."""
    if raw_file_id is None:
        return ''
    value = str(raw_file_id).strip()
    return value


def _build_file_key(file_id: str, name: str, filepath: str) -> str:
    """Build a collision-resistant key for the dfs cache."""
    if file_id:
        return f'id:{file_id}'
    if filepath:
        return f'path:{filepath}'
    return f'name:{name}'


def _set_name_alias(name: str, filepath: str, df: pd.DataFrame):
    """Preserve filename access while avoiding overwriting a non-empty alias with an empty frame."""
    if not name:
        return

    existing = session_state['dfs'].get(name)
    if isinstance(existing, pd.DataFrame) and not existing.empty and df.empty:
        return

    session_state['dfs'][name] = df
    session_state['file_sources'][name] = filepath


def load_files(files_json_str: str):
    """Load request files into the session state and refresh stale filename collisions."""
    try:
        files = json.loads(files_json_str)
    except (json.JSONDecodeError, TypeError):
        return []

    requested_keys = []

    for f in files:
        filepath = f.get('path', '')
        name = f.get('name', '')
        file_id = _normalize_file_id(f.get('id'))
        if not filepath or not name:
            continue

        file_key = _build_file_key(file_id, name, filepath)
        requested_keys.append(file_key)

        cached_path = session_state['file_sources'].get(file_key)
        cached_df = session_state['dfs'].get(file_key)
        should_reload = (
            cached_path != filepath
            or not _is_usable_frame(cached_df)
        )

        if not should_reload:
            _set_name_alias(name, filepath, cached_df)
            continue

        ext = os.path.splitext(filepath)[1].lower()
        try:
            loaded_df = None
            if ext == '.csv':
                loaded_df = read_csv_flexible(filepath)
            elif ext in ['.xlsx', '.xls']:
                # Advanced Sheet Discovery: Scan all sheets and pick the richest one
                xl = pd.ExcelFile(filepath)
                sheet_scores = []

                for sheet_name in xl.sheet_names:
                    temp_df = pd.read_excel(filepath, sheet_name=sheet_name)
                    # Cleaning to get honest count
                    temp_df = temp_df.dropna(how='all').dropna(axis=1, how='all')
                    score = len(temp_df) * len(temp_df.columns)
                    sheet_scores.append((score, sheet_name, temp_df))

                # Sort by score descending and take the winner
                sheet_scores.sort(key=lambda x: x[0], reverse=True)
                df = sheet_scores[0][2] if sheet_scores else pd.DataFrame()

                # Robust cleaning
                df = df.dropna(how='all').dropna(axis=1, how='all')

                # Only search for a header row if columns look auto-generated
                if _columns_look_autogenerated(df) and len(df.columns) > 0:
                    header_found = False
                    for i in range(min(15, len(df))):
                        row = df.iloc[i]
                        non_null_count = row.notnull().sum()
                        if non_null_count >= 2 and row.nunique() >= non_null_count * 0.8:
                            new_header = [str(h).replace('\n', ' ').strip() for h in df.iloc[i]]
                            candidate_df = df.iloc[i+1:].copy()
                            candidate_df.columns = new_header
                            candidate_df = candidate_df.dropna(how='all').dropna(axis=1, how='all')
                            # Only accept the new header if it leaves data rows
                            if len(candidate_df) > 0:
                                df = candidate_df
                                header_found = True
                            break

                    # If no header found, assign generic column names
                    if not header_found and len(df) > 0:
                        df.columns = [f'Column_{i+1}' for i in range(len(df.columns))]

                # Fallback: if cleaning left 0 rows, re-read the best sheet with header=None
                if len(df) == 0 and sheet_scores:
                    raw_df = pd.read_excel(filepath, sheet_name=sheet_scores[0][1], header=None)
                    raw_df = raw_df.dropna(how='all').dropna(axis=1, how='all')
                    if len(raw_df) > 0:
                        new_header = [str(h).replace('\n', ' ').strip() for h in raw_df.iloc[0]]
                        df = raw_df.iloc[1:]
                        df.columns = new_header
                        df = df.dropna(how='all').dropna(axis=1, how='all')
                        if len(df) == 0:
                            df = raw_df.reset_index(drop=True)
                loaded_df = df.reset_index(drop=True)
            elif ext == '.json':
                loaded_df = read_json_flexible(filepath)
            elif ext == '.parquet':
                loaded_df = pd.read_parquet(filepath)
            elif ext == '.tsv':
                loaded_df = read_csv_flexible(filepath, forced_sep='\t')
            elif ext in ['.txt']:
                # Try CSV first, then raw text
                try:
                    parsed = read_csv_flexible(filepath)
                    if len(parsed.columns) < 2:
                        raise ValueError('single column text file')
                    loaded_df = parsed
                except Exception:
                    with open(filepath, 'r', encoding='utf-8', errors='replace') as fh:
                        content = fh.read()
                    loaded_df = pd.DataFrame({'text': content.split('\n')})

            if not isinstance(loaded_df, pd.DataFrame):
                loaded_df = pd.DataFrame({'load_error': [f'Unsupported file type for {name}: {ext}']})

            session_state['dfs'][file_key] = loaded_df
            session_state['file_sources'][file_key] = filepath
            _set_name_alias(name, filepath, loaded_df)
        except Exception as e:
            sys.stderr.write(f"Error: Could not load {name}: {str(e)}\n")
            failure_df = pd.DataFrame({'load_error': [f'Failed to load {name}: {str(e)}']})
            session_state['dfs'][file_key] = failure_df
            session_state['file_sources'][file_key] = filepath
            _set_name_alias(name, filepath, failure_df)

    return requested_keys


def execute_request(request: dict) -> dict:
    """Execute a single code request and return results."""
    code = request.get('code', '')
    files_json = request.get('files_json', '[]')

    # Load any new files
    requested_keys = load_files(files_json)

    dfs = session_state['dfs']
    df = pd.DataFrame()
    requested_dfs = [
        dfs.get(key) for key in requested_keys
        if _is_usable_frame(dfs.get(key))
    ]

    if requested_dfs:
        df = requested_dfs[0]
    elif dfs:
        usable_df = next(
            (candidate for candidate in dfs.values() if _is_usable_frame(candidate)),
            None,
        )
        df = usable_df if usable_df is not None else pd.DataFrame()

    # Build execution namespace with all available tools
    namespace = {
        'pd': pd,
        'np': np,
        'dfs': dfs,
        'df': df,
        'file_sources': session_state['file_sources'],
        'result': None,
        'plotly_json': [],
        'os': os,
        'json': json,
        'base64': base64,
        'BytesIO': BytesIO,
    }

    # Add optional libraries
    if HAS_MPL:
        namespace['plt'] = plt
        namespace['sns'] = sns
        namespace['matplotlib'] = matplotlib
    if HAS_PLOTLY:
        namespace['px'] = px
        namespace['go'] = go
        namespace['pio'] = pio
        namespace['make_subplots'] = _make_subplots
    if HAS_SCIPY:
        namespace['scipy_stats'] = scipy_stats
    if HAS_SKLEARN:
        namespace['preprocessing'] = preprocessing
        namespace['cluster'] = cluster
        namespace['decomposition'] = decomposition
        namespace['ensemble'] = ensemble
        namespace['linear_model'] = linear_model
        namespace['metrics'] = metrics
        namespace['sklearn'] = __import__('sklearn')

    # Merge persisted variables
    namespace.update(session_state['variables'])

    try:
        # Execute the code
        exec(code, namespace)

        # Extract result
        result = namespace.get('result', None)
        result_str = ''
        if result is not None:
            if isinstance(result, pd.DataFrame):
                result_str = result.to_string(max_rows=50, max_cols=20)
            elif isinstance(result, pd.Series):
                result_str = result.to_string(max_rows=50)
            else:
                result_str = str(result)
        else:
            result_str = 'Execution successful'

        # Capture matplotlib charts
        charts = []
        if HAS_MPL:
            for fig_num in plt.get_fignums():
                fig = plt.figure(fig_num)
                buf = BytesIO()
                fig.savefig(buf, format='png', dpi=150, bbox_inches='tight',
                           facecolor='#0a0a0a', edgecolor='none',
                           transparent=False)
                buf.seek(0)
                charts.append(base64.b64encode(buf.read()).decode('utf-8'))
                plt.close(fig)

        # Capture plotly charts
        plotly_raw = namespace.get('plotly_json', [])
        if isinstance(plotly_raw, list):
            plotly_charts = list(plotly_raw)
        elif plotly_raw is None:
            plotly_charts = []
        else:
            plotly_charts = [plotly_raw]

        def _dedupe_plotly(items):
            unique_items = []
            plotly_seen = set()
            for item in items:
                try:
                    normalized = json.loads(json.dumps(item, cls=SafeJSONEncoder))
                    signature = json.dumps(normalized, sort_keys=True, cls=SafeJSONEncoder)
                except Exception:
                    normalized = item
                    signature = None

                if signature is not None:
                    if signature in plotly_seen:
                        continue
                    plotly_seen.add(signature)

                unique_items.append(normalized)
            return unique_items

        plotly_charts = _dedupe_plotly(plotly_charts)
        
        # Also check if result is a Plotly figure and auto-discover figures in namespace.
        if HAS_PLOTLY:
            discovered_plotly = []

            def _append_plotly_chart(value):
                try:
                    if value is None:
                        return
                    if hasattr(value, 'to_plotly_json'):
                        chart_json = value.to_plotly_json()
                        discovered_plotly.append(json.loads(json.dumps(chart_json, cls=SafeJSONEncoder)))
                    elif isinstance(value, dict) and 'data' in value and 'layout' in value:
                        discovered_plotly.append(json.loads(json.dumps(value, cls=SafeJSONEncoder)))
                except Exception:
                    pass

            _append_plotly_chart(result)

            for key, value in namespace.items():
                if key.startswith('__'):
                    continue
                _append_plotly_chart(value)

            if discovered_plotly:
                plotly_charts.extend(_dedupe_plotly(discovered_plotly))

        # Ensure output is always a list for UI rendering.
        if not isinstance(plotly_charts, list):
            plotly_charts = [plotly_charts]

        plotly_charts = _dedupe_plotly(plotly_charts)

        if len(plotly_charts) > 0:
            result_str = 'Interactive chart generated'

        # Get updated df sample
        updated_df_sample = None
        current_df = namespace.get('df', None)
        if isinstance(current_df, pd.DataFrame) and not current_df.empty:
            sample_df = current_df.head(5).copy()
            # Convert datetime columns to strings for safe serialization
            for col in sample_df.columns:
                if pd.api.types.is_datetime64_any_dtype(sample_df[col]):
                    sample_df[col] = sample_df[col].astype(str)
            updated_df_sample = json.loads(json.dumps(sample_df.replace({np.nan: None}).to_dict(orient='records'), cls=SafeJSONEncoder))

        # Persist variables for future calls (exclude builtins, modules)
        skip_keys = {'pd', 'np', 'plt', 'sns', 'px', 'go', 'pio', 'dfs', 'df', 'result',
                     'plotly_json', 'os', 'json', 'base64', 'BytesIO', 'matplotlib',
                     'scipy_stats', 'preprocessing', 'cluster', 'decomposition',
                     'ensemble', 'linear_model', 'metrics', 'sklearn',
                     'make_subplots', 'file_sources', '__builtins__'}
        for k, v in namespace.items():
            if k not in skip_keys and not k.startswith('__'):
                try:
                    json.dumps(v, cls=SafeJSONEncoder)  # Only persist serializable objects
                    session_state['variables'][k] = v
                except (TypeError, ValueError):
                    pass  # Skip non-serializable objects (but they stay in namespace)

        return {
            'success': True,
            'result': result_str[:15000],  # Cap result length (increased for full output)
            'charts': charts,
            'plotly_charts': plotly_charts,
            'updated_df_sample': updated_df_sample
        }

    except Exception as e:
        tb = traceback.format_exc()
        return {
            'success': False,
            'result': '',
            'error': str(e),
            'traceback': tb,
            'charts': [],
            'plotly_charts': []
        }


def main():
    """Main loop — reads JSON requests from stdin, writes results to stdout."""
    for line in sys.stdin:
        line = line.strip()
        if not line:
            continue
        try:
            request = json.loads(line)
            result = execute_request(request)
            sys.stdout.write(json.dumps(result, cls=SafeJSONEncoder) + '\n')
            sys.stdout.flush()
        except json.JSONDecodeError:
            error_result = {
                'success': False,
                'error': 'Invalid JSON request',
                'result': '',
                'charts': [],
                'plotly_charts': []
            }
            sys.stdout.write(json.dumps(error_result) + '\n')
            sys.stdout.flush()
        except Exception as e:
            error_result = {
                'success': False,
                'error': f'Kernel error: {str(e)}',
                'result': '',
                'charts': [],
                'plotly_charts': []
            }
            sys.stdout.write(json.dumps(error_result) + '\n')
            sys.stdout.flush()


if __name__ == '__main__':
    main()
